### ISSUE TITLE
Publish amd64 images

### ISSUE THREAD

**Issue by buroa** [WillFantom/overseerr-exporter#2]
Getting a format error when running these, so I had to build my own containers for `amd64`.

**Comment by WillFantom** [comment]
Thanks for pointing this out 👍 I've updated the CI to push images for a good array of platforms now (`linux/amd64`, `linux/386`, `linux/arm64`, `linux/arm/v6`, `linux/arm/v7`)

**Comment by buroa** [comment]
Thanks!
